[application]

# App (Project) Name
name = "chordflow_desktop"
default_platform = "desktop"

asset_dir = "assets"

[web.app]

# HTML title tag content
title = "chordflow_desktop"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["assets/tailwind.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
resources = ["assets/*"]
identifier = "io.timnology"
publisher = "Timnology"
icon = ["icons/icon-512.png", "icons/AppIcon.icns"]
